### PR TITLE
Feature to relax all querqy FILTER rules via automatic addition of an "OR" filter query #306

### PR DESCRIPTION
**Pull request by Paul-Blanchaert**
See #306

### CODE REVIEW

**Comment by renekrie** [comment]
Thank you @Paul-Blanchaert !

I have to think a bit about this but maybe that's good enough first thoughts to start the discussion:

I think this could go directly into QuerqyQueryComponent if you renamed the config parameter `fq` to something like `alternativeFilterQuery` (not sure if that's the best name but the idea would be to express that this is an alternative match that is combined with the generated filter queries). If that parameter is not set, no alternative would be added.

I'm wondering if that should better be a per-request parameter. Parsing the query string is pretty cheap and we'd achieve a lot more flexibility if we set this parameter per request. (That would maybe give us a parameter `querqy.fq.alt` instead of the above `alternativeFilterQuery`).

Finally, I wonder if the behaviour could be rewriter-specific, one rewriter being okay with this alternative, the other strictly wanting to see applied its filter. In that case the parameter should be set per rewriter  (à la `querqy.<myrewriterId>.fq.alt`) - but the implementation would have to move to the rewriter itself (and be applied at the Querqy query object model, not at the Lucene level).

I think currently the only rewriter that adds filters is the CommonRulesRewriter. Would you find the place where it adds the filters and could you add the Boolean-Or there @Paul-Blanchaert ? The value of `querqy.<myrewriterId>.fq.alt` would probably be in Solr syntax so you could wrap that query string into a querqy.model.StringRawQuery and it would get parsed into a Lucene query automatically. - I think that's best solution (but I needed to write down all this thread to come to this conclusion ;-) )

**Comment by Paul-Blanchaert** [comment]
@renekrie, I was lacking some inspiration on the parameter name fq. fq is indeed associated with filtering vs relaxing of the filter... But then fq.alt makes me think on q.alt, where the function is a bit different. So I would vote for us to come up with a better parameter name....
I also thought on the request parameter option, but it felt like almost too flexible... but maybe that is due to the case I'm looking at... and flexibility is usually a good thing... I also like the per rewriter suggestion. So let's use request parameters.
I will have a second look in order to put the logic in during the addition of the filter queries instead of rewriting them as currently in this PR.

**Comment by renekrie** [comment]
Hey @Paul-Blanchaert, Thank you very much again for your work. Are you planning to move this to the CommonRules rewriter?

**Comment by Paul-Blanchaert** [comment]
Hi @renekrie 
I had a look at this...
I think we should call this "filter complement" as it basically complements the filter instruction. Suggested parameter would be "querqy.fc" or "querqy.<myrewriterId>.fc".
I could use some directions on moving to CommonRulesRewriter...
The filterinstructions in querqy-core generate a RawQuery or a BooleanQuery. As we want to use a request parameter with  the querystring for the "filter component", we need to parse this string to a QuerqyQuery (not for the RawQuery as that can handle the querystring, but for the BooleanQuery). I can use the QuerqyParserFactory.createParser, parse the querystring and place it in the context to be used when adding filterinstructions. But that queryparser is not taking care of fieldnames so we need to handle that for this function only.
The alternative (that might be better) is to perform the addition in QuerqyParsingController.transformFilterQueries(...) in querqy-lucene, but here we don't have the rewriter id (so we would need to drop the querqy.<myrewriterId>.fc parameter value or store the rewriter id and applicable filterinstruction somewhere on the ExpandedQuery).
I'll commit the first approach for your review.
Looking forward to your feedback

**Pull request closed without merging**
