### PR TITLE
Allowing escaping of `*`, `"`, `#` and `\` for rule input

### PR DESCRIPTION
**Pull request by mkr**
A first shot at allowing escaping of some characters in rules input for common rules rewriter.

### CODE REVIEW

**Comment by renekrie** [comment]
Could you please provide a test that shows that escaping works together with the escaping that's already in place for boolean expressions - (see  https://github.com/querqy/querqy/blob/master/querqy-core/src/test/java/querqy/rewrite/commonrules/select/booleaninput/BooleanInputParserTest.java#L18)

**Review by renekrie — CHANGES_REQUESTED** [review]
See comment in main conversation re escaping Boolean Expressions.

Also, please make method params final.

Thanks!

**Comment by mkr** [comment]
@renekrie the code is a bit messy there:
* BooleanInputParser handles quote and wildcard as literal values already and does not treat them in any special way so escaping for them would be unnecessary.
* I could still add it to be consistent with the other code paths in Input#fromString that use Input#parseSimpleInput.

**Comment by mkr** [comment]
@renekrie ok, i have added the unescaping also to the BooleanInputParser adhering to the code style there.

**Review by renekrie — APPROVED** [review]
Thank you @mkr !

**Pull request merged**
