### PR TITLE
Making rewriter data dir configurable in ZK. Fixes #263

### LINKED ISSUE #263: Solr 'Restore backup' doesn't bring back .data directory
When restoring a backup in Solr, the rewriter data directory (`.data`) will not be restored to ZooKeeper as the dot in the name makes it a hidden directory.

Solution: rename the directory.

### PR DESCRIPTION
**Pull request by renekrie**
The  rewriter config data dir can now be configured: 

```xml
<requestHandler name="/querqy/rewriter" class="querqy.solr.QuerqyRewriterRequestHandler">
    <str name="zkDataDirectory">__data</str>
</requestHandler>
```

This allows to configure a directory name that is visible when restoring Solr backups from the file system (unlike the default name `.data`)

### CODE REVIEW

**Comment by epugh** [comment]
maybe too late to comment, but what if the default wasn't ".data" and so you didn't need this?  Won't everybody now need to add `<str name="zkDataDirectory">__data</str>` to their config in case they want to do backups?

**Comment by renekrie** [comment]
I chose to leave `.data` as the default, as this seemed to be the only save path to migrate existing installations safely without stopping the entire SolrCloud: The old Querqy version would always try to read from `.data`.

In the new version, you can always decide to change your rewriter directory later (and thus go from `.data` to a non-default directory that's configured in `<str name="zkDataDirectory">__data</str>`. There will be a file `querqy/rewriters/my_rewriter_name` which contains the location of the rewriter configuration (usually `.data`) from where the rewriter config is read. When you change the location via `<str name="zkDataDirectory">__data</str>`, next time you save the rewriter config, it will be written to the new place and `querqy/rewriters/my_rewriter_name` will point to the new location. That means, you'd have to save all rewriters once if you want to move them to he new location.

**Comment by renekrie** [comment]
One more thought on this. We'd be in trouble if someone tried to name their rewriter like that directory. We'd have the file that stored the rewriter info: 

`querqy/rewriters/my_rewriter_name`

and the data dir:

`<str name="zkDataDirectory">my_rewriter_name</str>`

- both pointing to the same ZK node. That's why I chose `.data` in the first place, assuming that no one would start their rewriter name with a dot (and also protect it in the code). That's a lot more difficult now as rewriter directories can change over time. We'd now always protect everything that starts with a dot and the current value of `zkDataDirectory`.

Finally, I think that this issue is more or less an issue (bug?) in Solr's 'restore' procedure when it uses a file system for backup/restore. Why would it back up `.data` but not restore?

**Comment by epugh** [comment]
> Why would it back up .data but not restore?

That is a great question.   Do we want to spin up a seperate ticket, either here or in Solr JIRA?

**Comment by renekrie** [comment]
Let's do that in Solr JIRA and decouple the Querqy workaround from that.

**Pull request merged**
