### PR TITLE
Changes response key  to querqy_rewriteLogging. Fixes #317

### LINKED ISSUE #317: Inconsistent formatting of response from Querqy in Solr
We have both `querqy.infoLog` AND `querqy_decorations`...   Seems like we should follow one pattern or the other!   To reduce chance of error and cognitive load on all the new folks adopting Querqy ;-)

### PR DESCRIPTION
**Pull request by renekrie**

### CODE REVIEW

**Review by JohannesDaniel — COMMENTED** [review]
How about `rewriteLogging`?

We should either use camel case or snake case, but not both...

**Comment by renekrie** [comment]
We would also have to change `querqy_decorations`  and `querqy_named_decorations`.  I'd like to keep a prefix that points to Querqy, so I guess it would have to be `querqy_rewrite_logging` @JohannesDaniel ?

**Comment by JohannesDaniel** [comment]
But the rest of Solr is camel case and not snake case, right? So I think we should stick to camel case from now on

**Comment by renekrie** [comment]
I finally went for camel case as we are also using it in the child elements of `querqyRewriteLogging`. Decorations remain snake case as changing it would break a lot of applications, including those that use SMUI. Should we ever touch decorations, we should also switch to using camel case there.

**Review by JohannesDaniel — APPROVED** [review]

**Pull request merged**
